services:
  web:
    container_name: f8-k19-b43
    image: node:25
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    ports:
      - 5173:5173
    command: ["npm", "run", "dev", "--", "--host"]
